### ISSUE TITLE
Java Builder pattern for code chaining

### ISSUE THREAD

**Issue by wolfposd** [pascaldekloe/colfer#21]
currently all "setValue(Value x)" methods return _void_ , if they would return the object then code-chaining would become possible.

example current:

```java
SomeClass sc = new SomeClass();
sc.setValue(42);
sc.setStringValue("string");
```

example builder pattern:

```java
SomeClass sc = new SomeClass().setValue(42).setStringValue("string");
```

**Comment by pascaldekloe** [comment]
Sounds like a win.
 Does the signature change for setters break property detection on frameworks such as JAX-B, JPA, Spring and whatever is used these days?

**Comment by wolfposd** [comment]
the standard JavaBean Introspection specifies that setters must comply with "_void setValue(T value)_"
But Hibernate and Spring also support "_T setValue(T value)_"

so its either:
- create setter methods that look like "_T setValue(T value)_" and break standard JavaBean Introspection
- create additional setters like "_T value(T value)_"


also, JAXB has a fluent-api which generates "_T withValue(T value)_" from schema files

**Comment by pascaldekloe** [comment]
The builder setter (without "set" prefix) is quite nice. The only problem I can think of is name collisions. The following would generate both `void setInstant(boolean)` and `Boo setInstant(boolean)`.

```
type boo struct {
        setInstant bool
        instant    bool
}
```

As an alternative Colfer could generate something like `Boo#builder() Boo.Builder` and `Boo.Builder#build() Boo`. :thinking:

Kind of unbelievable that you need all this code just because Java doesn't have proper literals while there is AutoCloseable, Lambda expressions and such.

**Comment by wolfposd** [comment]
using a Boo.Builder class is an alternative some other projects are using

`Boo boo = Boo.Builder.newBuilder().setInstant(true).setSetInstant(true).build();`

**Comment by pascaldekloe** [comment]
Went for the "fluent API" after all. Thanks for guiding the process. :-)
