### ISSUE TITLE
Support reading/writing to/from Input/OutputStreams

### ISSUE THREAD

**Issue by jschneider** [pascaldekloe/colfer#3]
Seems to be more convenient for the Java user.

**Comment by pascaldekloe** [comment]
Indeed. Covering common cases also prevents bugs since the marshal and unmarshal methods ain't that simple.

The Java core library interfaces are less than optimal.
* `java.util.Iterator` requires something like `java.io.UncheckedIOException`
* `java.io.ObjectInputStream` and `java.io.ObjectOutputStream` are bloated
* `javax.xml.bind` is extremely bloated

This is the best I can come up with. Ideas are welcome.

`static java.io.ObjectInputStream reader(InputStream source, byte[] initialBuffer)`

`static java.io.ObjectOutputStream writer(OutputStream target, byte[] initialBuffer)`
