### ISSUE TITLE
partial unmarshal java

### ISSUE THREAD

**Issue by tamerh** [pascaldekloe/colfer#43]
Hello,

A question. I have my serialized colfer byte array inside a `ByteBuffer`.  And i would like to access just some specific fields. Is this possible without loading everything or i should write a customised version of generated unmarshal method? 

Regards
Tamer

**Comment by pascaldekloe** [comment]
Hi Tamer,

That's an interesting feature indeed. I want binary lookups quite badly too.
The short answer is no, the compiler doesn't support single field extraction at the moment. For €22k I could realise non-nested lookups as in `colf -F person.name,person.phone Java address.colf` with:

```java
/**
 * Extracts the name field from a Person serial.
 * @buf the data source.
 * @return the field value.
 */
public static String colferName(byte[] buf) {
```

Otherwise you could create your own with a bit of work. The generated Go code also includes
[serial size counting](https://github.com/pascaldekloe/colfer/blob/fc51d07850985ee0a3c50174d73f4bf70ecc6632/go/gen/Colfer.go#L357)
which is pretty close to what you'd need when skipping fields.
