### ISSUE TITLE
Define Null-able types in some languages

### ISSUE THREAD

**Issue by guilt** [pascaldekloe/colfer#65]
Use the tags API to generate NULL-able types in some languages.

I may want to use `Integer` instead of `int` in Java, where 0 may be a valid value but considered set by the user. I actually require it for the application, would convert the `if(x == 0)` into: `if (x == null || x == 0)` check for those types.

**Comment by guilt** [comment]
I sadly require this to be able to use it in an older application, would appreciate it if we can design rules around this. I wanted to change the template in `java.go` but it may not be ideal if nobody else wants this change.

**Comment by pascaldekloe** [comment]
See https://github.com/pascaldekloe/colfer/issues/17#issuecomment-278302528

In short, use a `hasFoo` boolean for integer `foo`.  Javas primitive objects are slow and cumbersome. Those endless null checks are a plague.

**Comment by guilt** [comment]
I understand how slow they are. Not everyone designs with that in mind, and sometimes an in-between solution is required. I'd like you to consider giving people the alternative for other templates as well, in case the original templates are not usable for some reason.

**Comment by pascaldekloe** [comment]
When you offer people bad options they will use it. You've worked for Amazon, so then you know from experience what happens when you listen to customers without vision. Their APIs make extensive use of (string) pointers too. 🤮 As a result their users panic once in a while, because someone always forgets a null check somewhere.

In other words: I don't want bad design to fit well. Make undefined states explicit (by design). By narrowing the options you lead people in the right direction.

I try really hard to provide little functionality, and then make that work really well. Adding bells and whistles to keep everyone happy leads to a mess.
